"""create initial clara schema

Revision ID: 0090a3ff2e84
Revises: 
Create Date: 2026-05-08 15:31:19.675544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0090a3ff2e84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('lead_temperature', sa.String(length=20), nullable=False),
    sa.Column('raw_filename', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_extractions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('lead_temperature', sa.String(length=20), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=50), nullable=False),
    sa.Column('buying_intent', sa.String(length=20), nullable=False),
    sa.Column('sentiment', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('main_objections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('budget_signal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_reply_strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('customer_summary', sa.Text(), nullable=False),
    sa.Column('next_best_action', sa.Text(), nullable=False),
    sa.Column('content_insight', sa.Text(), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_extractions_conversation_id'), 'ai_extractions', ['conversation_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('sender_type', sa.String(length=50), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('message_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('reply_suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('ai_extraction_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('action_mode', sa.String(length=50), nullable=False),
    sa.Column('approval_status', sa.String(length=50), nullable=False),
    sa.Column('suggested_replies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_reply_text', sa.Text(), nullable=True),
    sa.Column('final_reply_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_extraction_id'], ['ai_extractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reply_suggestions_ai_extraction_id'), 'reply_suggestions', ['ai_extraction_id'], unique=False)
    op.create_index(op.f('ix_reply_suggestions_conversation_id'), 'reply_suggestions', ['conversation_id'], unique=False)
    op.create_table('approval_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reply_suggestion_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('before_text', sa.Text(), nullable=True),
    sa.Column('after_text', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reply_suggestion_id'], ['reply_suggestions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_logs_reply_suggestion_id'), 'approval_logs', ['reply_suggestion_id'], unique=False)
    op.create_table('sent_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('reply_suggestion_id', sa.Uuid(), nullable=True),
    sa.Column('send_mode', sa.String(length=50), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('sent_by_name', sa.String(length=255), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_suggestion_id'], ['reply_suggestions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sent_messages_conversation_id'), 'sent_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sent_messages_reply_suggestion_id'), 'sent_messages', ['reply_suggestion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sent_messages_reply_suggestion_id'), table_name='sent_messages')
    op.drop_index(op.f('ix_sent_messages_conversation_id'), table_name='sent_messages')
    op.drop_table('sent_messages')
    op.drop_index(op.f('ix_approval_logs_reply_suggestion_id'), table_name='approval_logs')
    op.drop_table('approval_logs')
    op.drop_index(op.f('ix_reply_suggestions_conversation_id'), table_name='reply_suggestions')
    op.drop_index(op.f('ix_reply_suggestions_ai_extraction_id'), table_name='reply_suggestions')
    op.drop_table('reply_suggestions')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_ai_extractions_conversation_id'), table_name='ai_extractions')
    op.drop_table('ai_extractions')
    op.drop_table('conversations')
    # ### end Alembic commands ###
